### ISSUE TITLE
Is this work with Laravel 5.4

### ISSUE THREAD

**Issue by sudesh10** [DeSmart/pagination#14]
is this work with Laravel 5.4

**Comment by radmen** [comment]
In terms of composer dependencies - definitely not. In terms of compatibility with Laravel 5.4 - probably not. This package is not maintained anymore.

**Comment by namnguyen2091** [comment]
@radmen do you understand how pagination works? I need to custom return data like this but I dont know how to extend service provider, i'm using laravel 5.7:
```
{
   "paginator": {// my custom code},
   "data":[
        {
            // Result Object
        },
        {
            // Result Object
        }
   ]
}
```
instead of default:
```
{
   "total": 50,
   "per_page": 15,
   "current_page": 1,
   "last_page": 4,
   "first_page_url": "http://laravel.app?page=1",
   "last_page_url": "http://laravel.app?page=4",
   "next_page_url": "http://laravel.app?page=2",
   "prev_page_url": null,
   "path": "http://laravel.app",
   "from": 1,
   "to": 15,
   "data":[
        {
            // Result Object
        },
        {
            // Result Object
        }
   ]
}
```

**Comment by radmen** [comment]
@namnguyen2091 You're using this package, or is your question related with service providers themselves?

Either way - don't extend service provider. Write your own provider and extend the IoC binding. When required, you can even replace previous bindings with your own (as it's done in this package).

**Comment by namnguyen2091** [comment]
@radmen I dont use this package. I dont know which method is right, I've ever heard about IOC but Im still a newbie. Please guide me more, I understand what you said but I dont know how to do.

**Comment by radmen** [comment]
@namnguyen2091 I think you should take a look at the [Laravel docs](https://laravel.com/docs/5.7/container). They're good enough to start with.

Once you get the concept behind IoC container and service providers you should write your own paginator class (or extend the existing one) and bind it using Service Provider with the IoC container.

**Comment by namnguyen2091** [comment]
my god, i think you dont know how pagination service work. Once again, I know SP and IOC but I dont know bind to what. Thanks.

**Comment by radmen** [comment]
@namnguyen2091 This package was created a few years ago. Back then I knew exactly how it worked :) I assume that the principle remained the same, yet it might have changed.

If you want to bind own implementation of paginator just look at the sources of Laravel and trace bindings for it. With that, you should be able to write own SP which will overwrite this binding.

Your problem is not related to this issue. Furthermore - since the package is not maintained anymore I'm going to close the issue.

**Comment by namnguyen2091** [comment]
I spent two days to research this problem but there is no solution can help me solve, I found Paginator object is autoload somewhere but its only allow custom some attributes. So I think the best way and easy way is take result from query and transform it with my custom class, and the awesome way is modify Paginator core class =)) and maybe autoload my custom paginator instead of laravel paginator.

Conclusion:
- This package only work with Laravel <= 5.3
- This package helps me know more knowedge about laravel
